### ISSUE TITLE
แบบฟอนต์ที่จะใช้กับเว็บไซต์

### ISSUE THREAD

**Issue by goslife** [pchaow/kwanphayao#25]
เมื่อได้แบบฟอนต์ที่ต้องการ อยากได้ ไฟล์ .TTF เพื่อนำมาเป็นเป็นไฟล์
.eot ใช้สำหรับแสดงฟอนต์ ใน IE8 ขึ้นไป http://caniuse.com/#feat=eot หรือ
.svg ใช้สำหรับแสดงฟอนต์ทุกอุปกรณ์ ยกเว้น IE8 และ Android 4.1-4.3 http://caniuse.com/#feat=svg หรือ
.woff ใช้สำหรับแสดงฟอนต์ ใน IE9 ขึ้นไป และ iOS5 ขึ้นไป http://caniuse.com/#feat=woff
ที่มา http://stackoverflow.com/questions/11002820/why-should-we-include-ttf-eot-woff-svg-in-a-font-face

**Comment by ratanapat** [comment]
font สำหรับปุ่ม ต่างๆ - Kunlasatri-Bold_0
สำหรับ heading - supermarket_0
