### ISSUE TITLE
Visual design หน้าเว็บไซต์ แจ้งเตือนข้อผิดพลาดต่างๆ

### ISSUE THREAD

**Issue by goslife** [pchaow/kwanphayao#26]
-หน้า 403 Forbidden หน้าที่แจ้งเตือนว่า หน้า หรือ path นี้ เข้าไม่ได้ เมื่อ user ไม่มีระดับสิทธิ์ในการเข้าถึง
เช่น ถ้ายังไม่ได้ login เข้าหน้าจัดการระบบไม่ได้ /admin อาจแจ้งเป็น "คุณไม่มีสิทธิ์เข้าถึงหน้าเว็บไซต์นี้" หรือ redirect มาหน้า login เลย (Optional)
-หน้า 404 not found (Request)
-หน้า แจ้งว่า ระบบอยู่ระหว่างปรับปรุง (Optional)

**Comment by goslife** [comment]
ตัวอย่างหน้า แจ้งเตือนข้อผิดพลาดต่างๆ เช่น
error 401
![2015-03-05-03-58-22](https://cloud.githubusercontent.com/assets/919501/6493372/e3f5743a-c2ec-11e4-940c-3afe2b7551c2.png)

error 404
![2015-03-05-03-57-43](https://cloud.githubusercontent.com/assets/919501/6493379/efad509a-c2ec-11e4-9a03-7e1040e34188.png)

error 500
![2015-03-05-03-57-00](https://cloud.githubusercontent.com/assets/919501/6493384/f6f60748-c2ec-11e4-82bc-323d8bd1be30.png)

error อื่นๆ อะไรก็ตาม ก็แสดง error code ตามนั้น เช่น 503 เป็นต้น
![2015-03-05-03-53-21](https://cloud.githubusercontent.com/assets/919501/6493389/fdbacd02-c2ec-11e4-9b1e-b6cb89f996c7.png)

**Comment by pchaow** [comment]
สวยมากครับ งานหลังบ้านตอนนี้ยังไม่ก้าวหน้าเลย อิอิ
