### ISSUE TITLE
ออกแบบไอคอนสำหรับ 5 หมวดสาระความรู้

### ISSUE THREAD

**Issue by ratanapat** [pchaow/kwanphayao#49]
1. ข้อมูลทั่วไปกว๊านพะเยา
2. นิเวศวิทยาและสิ่งแวดล้อม
3. เศรษฐกิจและการท่องเที่ยว
4. การจัดการทรัพยากรธรรมชาติ
5. ประวัติศาสตร์และวัฒนธรรม

- เป็นไอคอนรูปวงกลม Flat Design บ่งบอกถึงลักษณะเฉพาะของหมวดนั้น อย่างเข้าใจง่ายในแวบแรกที่เห็น
- มีข้อความชื่อหมวด กำกับ ไว้ เพื่อให้เข้าใจง่ายมากยิ่งขึ้น
- เมื่อนำเมาส์ไปวาง จะเปลี่ยนสี

**Comment by goslife** [comment]
ลักษณะเฉพาะของแต่ละหมวด ที่เข้าใจง่ายในครั้งแรกที่เห็น ควรมีลักษณะอย่างไร
1. ข้อมูลทั่วไปกว๊านพะเยา           : ตราประจำ จ.พะเยาไหม
2. นิเวศวิทยาและสิ่งแวดล้อม       : รูปปลา หรือ พันธุ์ไม้น้ำอะไร
3. เศรษฐกิจและการท่องเที่ยว      : รูปเงินตรา หรือ รถยนต์ เครื่องบิน
4. การจัดการทรัพยากรธรรมชาติ   : รูปหยดน้ำ หรือ อะไร
5. ประวัติศาสตร์และวัฒนธรรม     : วัดหรือโบราณวัตถุ/สถาน ที่เป็นสัญลักษณ์ของ จ.พะเยา ไหม

**Comment by ratanapat** [comment]
นาวได้ออกแบบทั้ง5หมวดเรียบร้อยละจ้า ดูได้ในกูเกิลไดรฟเลย ในfolder: ออกแบบหน้าเว็บ\ icon_5หมวดสารานุกรม

**Comment by goslife** [comment]
ทำเสร็จแล้ว
![complete_maincategory24-2-2015 01-41-42](https://cloud.githubusercontent.com/assets/919501/6334452/43d97f04-bbc7-11e4-9f5a-bf08decd19f2.jpg)
