### ISSUE TITLE
feature request: get relations of services.js in User or Category

### ISSUE THREAD

**Issue by goslife** [pchaow/kwanphayao#53]
อยากได้ services สำหรับรับค่า ความสัมพันธ์ เช่น
User นี้ มีความสัมพันธ์ USER กับ Role เป็นอะไร หรือ Category นี้ มีความสัมพันธ์เป็น HAS_CATEGORY กับ MainCategory เป็นอะไร จะเอาไปส่งให้ $scope.user.role หรือ $scope.user.parent ในหน้า Edit

**Comment by ratanapat** [comment]
ไม่แน่ใจว่านาวเข้าใจถูกป่าว
มี 2 Users
1. ผู้ดูแลระบบ(admin)  
2. ผู้แก้ไข(editor)

ผู้ดูแลระบบ(admin) มี Role ดังนี้ 
- จัดการบทบาท และการตั้งค่าของเพจ
- แก้ไขเนื้อหา
- เพิ่มเนื้อหา
- ลบเนื้อหา
- ตอบกลับข้อเสนอแนะ
- ลบ/บล็อกบุคคลออกจากเพจ
- เพิ่มบุคคลเข้ามาในเพจ
- ดูข้อมูลเชิงลึก เช่น ประวัติการเข้าใช้

ผู้แก้ไข (editor) มี Role ดังนี้ 
- แก้ไขเนื้อหา
- เพิ่มเนื้อหา
- ลบเนื้อหา
- ตอบกลับข้อเสนอแนะ

**Comment by pchaow** [comment]
น่าจะประมาณนี้แหละ ไว้ ถ้ามีเพิ่มเติม ก็เพิ่มใน นี้เรื่อยๆ ละกัน

**Comment by pchaow** [comment]
$scope.user.role เอาเป็น อันนี้ดีกว่า

**Comment by pchaow** [comment]
แก้ใน category ละ

**Comment by goslife** [comment]
เหลือประกาศ permission ของ admin กับ editor

**Comment by pchaow** [comment]
ตรงนี้ยังไม่ออกแบบ เดี๋ยวสร้าง ISSUE ใหม่เลย
