### ISSUE TITLE
ช่วยระบุข้อมูลที่ต้องการเก็บข้อมูลในแต่ละหมวดหมู่

### ISSUE THREAD

**Issue by pchaow** [pchaow/kwanphayao#76]
อยากให้ช่วยกันคิดดูว่า ในหมวดหมู่ต่างๆ นั้น มีการเก็บข้อมูลของเนื้อหาอย่างไรบ้าง
โดยเฉพาะ กลุ่มของหมวดหมู่ที่มีข้อมูลเป็นโครงสร้าง เช่น พันธ์ุปลา พันธุ์พืช 
หรือ ข้อมูลทางประวัติศาสตร์ บุคคลสำคัญ เป็นต้น

**Comment by goslife** [comment]
กอสว่าต้องเอาข้อมูลตัวอย่างมาดูนะ
แล้วดูว่า การเก็บข้อมูลแต่ละแบบ มีข้อดีข้อเสียอย่างไร จะได้ร่วมโหวตกัน

**Comment by ratanapat** [comment]
นาวคิดว่า ณ ตอนนี้ จากที่รวบรวมข้อมูลมา 
- ส่วนใหญ่จะเป็นข้อมูลที่เป็นบทความทั่วไป (ประกอบด้วย หัวเรื่อง ย่อหน้า อาจมีหัวข้อย่อย และ อาจมีการแบ่งเป็นข้อ 1 2 3) --> ซึ่งตรงนี้ editorสามารถใช้ WYSIWYG  https://editor.froala.com/  ได้สบาย

- และมีบางส่วนที่เป็นบทความด้วย แต่ประกอบด้วยข้อมูลตาราง ซึ่งถ้ามีoptionฟอร์มให้กรอก น่าจะช่วยeditorได้ (ซึ่งตอนแรกที่คิดไว่ว่า จะทำแบบในwordpressแบบที่นาวเคยให้ดู แต่คิดว่าน่าจะยากและควรโยกการพัฒนาตรงนี้ไปที่วิจัยPhase 2เลย  ดังนั้นจึงคิดว่าในPhaseนี้ จะทำเป็นฟอร์มแยกแต่ละอัน เป็น thumbnail ให้ editorเลือกแล้วกรอกได้เท่านั้น)
ซึ่งเท่าที่รวบรวมข้อมูลและบางส่วนยังไม่ได้พิมพ์เป็นไฟล์word จะมี

หมวดทั่วไป 
1. ผลิตภัณฑ์OTOPจังหวัดพะเยา ฟอร์มคือ ชื่อผลิตภัณฑ์(text field), ที่มา(text field), ระดับดาว 1-5 (drop down list), ที่ตั้ง (text filed), รูปภาพ(upload photo + add description)

หมวดนิเวศวิทยา
1.ปลาในกว๊านพะเยา ฟอร์มคือ พันธุ์ปลา (text field), ชื่อวิทยาศาสตร์(text field), ชื่อสามัญ(text field),บริเวณที่อยู่อาศัย(text area),อาหารทั่วไปของปลา (text field),ลักษณะทางกายภาพ(text area), รูปภาพ(upload photo + add description)
2. พรรณไม้น้ำในกว๊านพะเยา ฟอร์มคือ ประเภท/ชนิดพรรณไม้น้ำ(drop down list : ชายน้ำ/ลอยน้ำ/ใต้น้ำโผล่เหนือน้ำ),ชื่อสามัญ(text field), ชื่อวิทยาศาสตร์(text field)
3. แพลงตอนในกว๊านพะเยา ฟอร์มคือ ชื่อคลาส(text field), ชื่อวิทยาศาสตร์(text field)
4. สัตว์ไม่มีกระดูกสันหลังในกว๊านพะเยา ฟอร์มคือ ประเภท(drop down list : กุ้ง/แมลงน้ำ/หอย/ไส้เดือนน้ำ/ไส้เดือน), ชื่อสามัญ(text field), ชื่ออันดับ(text field), ชื่อวงศ์(text field)

หมวดประวัติศาสตร์
1. ลำดับการเปลี่ยนแปลงกว๊านพะเยา ฟอร์มคือ เวลา(text field), เหตุการณ์สำคัญ(text area)
2. วัดในกว๊านพะเยา ฟอร์มคือ ชื่อวัด(text field), ชื่อวัดตามจารึก, ชื่อปัจจุบัน,สร้างเมื่อ,สภาพปัจจุบัน(text area),หลักฐานทางโบราณคดี(text area),ที่ตั้ง(text area) พิกัดและตำแหน่ง(text field),สัมภาษณ์(text area) ,ผู้สัมภาษณ์(text area), ประวัติ(text area), รูปภาพ(upload photo + add description)

ณ ตอนนี้มีแค่นี้ค่ะ อาจมีเพิ่มเติมอีกค่ะ

**Comment by ratanapat** [comment]
ขอแก้ไขค่า

4. สัตว์ไม่มีกระดูกสันหลังที่ก้นกว๊านพะเยา ฟอร์มคือ ประเภท(drop down list : กุ้ง/แมลงน้ำ/หอย/ไส้เดือนน้ำ), ชื่อสามัญ(text field), ชื่ออันดับ(text field), ชื่อวงศ์(text field)
5. สัตว์ไม่มีกระดูกสันหลังที่ค้นพบในน้ำบริเวณที่มีพืชในกว๊านพะเยา ฟอร์มคือ ประเภท(drop down list : กุ้ง/แมลงน้ำ/หอย/ไส้เดือนน้ำ), ชื่อสามัญ(text field), ชื่ออันดับ(text field), ชื่อวงศ์(text field)

**Comment by pchaow** [comment]
เดี๋ยวเราจะต้องวิเคราะห์และสรุปอีกที อ่ะนะ งงนิดๆ

**Comment by pchaow** [comment]
จากที่ได้คุยกันกับ อ.มะนาว ไว้จะเพิ่มใน issue อื่นๆ
