### ISSUE TITLE
เพิ่ม what you see is what you get (WYSIWYG) editor เพื่อแก้ไข content

### ISSUE THREAD

**Issue by pchaow** [pchaow/kwanphayao#79]
issue จะเป็นการพูดคุยว่า ระบบสารานุกรม จะใช้ editor แบบไหน ตัวอย่าง

* https://editor.froala.com/
* http://www.tinymce.com/index.php
* http://ckeditor.com/download
* http://imperavi.com/redactor/ 
* และอื่นๆ มีตัวไหนที่น่าสนใจบ้าง

ตอนนี้เราเชียร์  https://editor.froala.com/

**Comment by pchaow** [comment]
http://tracks.roojoom.com/r/4164#/introduction อ่านรายละเอียดจากเว็บนี้ก็น่าสนใจ

**Comment by ratanapat** [comment]
เห็นด้วยกับเชาวน์
- ชอบงานออกแบบของfroala ที่เป็นflat design ดูแล้วน่าจะเข้ากับเว็บเราสุด 
- ฟังก์ชั่นเยอะดี แล้วเข้าใจง่าย เมื่อเทียบกะ imperavi ที่เป็นflat design เหมือนกัน (โดยเฉพาะส่วนการใส่รูป)
- แต่กลัวอย่างนึงคือ พอมีฟังก์ชั่นเยอะๆ สามารถเปลี่ยนสีฟ้อนต์ และมีขนาดแตกต่างกัน.. อาจกลายเป็นการปล่อยให้ editor กำหนดรูปแบบอย่างฟรีสไตล์ จนคุมโทนเว็บโดยรวมไม่ได้ 

แต่ยังไงก็คิดชอบfroalaที่สุดอ่ะ

**Comment by pchaow** [comment]
ok สรุป  https://editor.froala.com/
